### ISSUE TITLE
Conditional Sequence Generation example command throwing an error

### ISSUE THREAD

**Issue by JDaksh** [microsoft/evodiff#56]
I have the local environment for evodiff set up, got the uniref split from zenodo and I'm able to run all the unconditional generation example commands. 

When I try running the following (example) conditional generation command,
`python evodiff/generate_msa.py --model-type msa_oa_dm_maxsub --batch-size 1 --n-sequences 64 --n-sequences 256 --subsampling MaxHamming --start-msa`

I get the error

> Traceback (most recent call last):
>   File "/workspace/evodiff/evodiff/generate_msa.py", line 413, in <module>
>     main()
>   File "/workspace/evodiff/evodiff/generate_msa.py", line 138, in main
>     sample, _string = generate_msa(model, tokenizer, args.batch_size, args.n_sequences, args.seq_length,
>   File "/workspace/evodiff/evodiff/generate_msa.py", line 186, in generate_msa
>     valid_msas, query_sequences, tokenizer = get_valid_data(data_top_dir, batch_size, 'autoreg',
>   File "/workspace/evodiff/evodiff/generate_msa.py", line 351, in get_valid_data
>     dataset = A3MMSADataset(selection_type, n_sequences, max_seq_len, data_dir=os.path.join(data_top_dir,data_dir), min_depth=64)
>   File "/opt/conda/lib/python3.10/site-packages/evodiff/data.py", line 353, in __init__
>     all_files = np.array(all_files)[keep_idx]
> IndexError: index 0 is out of bounds for axis 0 with size 0

I tried the same command out in the docker cford38/evodiff and got the exact same error again.

How should I fix this?

**Comment by falcooon** [comment]
my you send me the version of evodiff before [Nov 15, 2024]? plz

i lose the version due to reload my computer operate system

thank you very much
